name = "serdde"
entry = "src/test_main.dd"

[cxx]
standard = "c++20"

[build]
dir = "build"

[targets.tests]
entry = "src/test_main.dd"
kind = "executable"

[targets.derive]
entry = "src/derive_main.dd"
kind = "executable"

[targets.config]
entry = "tests/config_main.dd"
kind = "executable"

[targets.enums]
entry = "tests/enum_main.dd"
kind = "executable"
